### ISSUE TITLE
Random lockups possibly related to HW JPEG compressor.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv#1295]
I'm starting to see random lock-ups after recent updates, it's more likely to happen when running find_edges.py (manual exposure, see the script), also when the cam locks-up the last buffer is likely corrupted, see the attached images.
script:
```python
import sensor, image, time

sensor.reset() # Initialize the camera sensor.
sensor.set_pixformat(sensor.GRAYSCALE) # or sensor.RGB565
sensor.set_framesize(sensor.QQVGA) # or sensor.QVGA (or others)
sensor.set_auto_exposure(False, exposure_us=2500)

clock = time.clock() # Tracks FPS.
while(True):
    clock.tick() # Track elapsed milliseconds between snapshots().
    img = sensor.snapshot() # Take a picture and return the imagee
    img.find_edges(image.EDGE_CANNY, threshold=(50, 80))
    print(clock.fps()) # Note: Your OpenMV Cam runs about half as fast while
```
GDB backtrack:
```
jpeg_compress (src=src@entry=0xfc68, dst=dst@entry=0xfc58, quality=quality@entry=50, realloc=realloc@entry=false) at imlib/jpeg.c:723
723	                if (JPEG_output_paused) {
(gdb) backtrace 
#0  jpeg_compress (src=src@entry=0xfc68, dst=dst@entry=0xfc58, quality=quality@entry=50, realloc=realloc@entry=false) at imlib/jpeg.c:723
#1  0x08096d7c in framebuffer_update_jpeg_buffer () at imlib/framebuffer.c:155
#2  0x080b2526 in sensor_snapshot (sensor=0x300010f8 <sensor>, image=0x3002b404, flags=<optimized out>) at ports/stm32/sensor.c:1450
#3  0x08070536 in py_sensor_snapshot (n_args=<optimized out>, args=<optimized out>, kw_args=<optimized out>) at modules/py_sensor.c:119
#4  0x080ca23a in fun_builtin_var_call (self_in=0x814fb00 <py_sensor_snapshot_obj>, n_args=0, n_kw=0, args=0xfdbc)
    at ../../py/objfun.c:126
#5  0x080d3b6c in mp_call_function_n_kw (fun_in=0x814fb00 <py_sensor_snapshot_obj>, n_args=0, n_kw=0, args=0xfdbc)
    at ../../py/runtime.c:652
#6  0x080d3c58 in mp_call_method_n_kw (n_args=<optimized out>, n_kw=<optimized out>, args=args@entry=0xfdb4) at ../../py/runtime.c:668
#7  0x080d5e14 in mp_execute_bytecode (code_state=code_state@entry=0xfda0, inject_exc=inject_exc@entry=0x0) at ../../py/vm.c:1090
#8  0x080ca300 in fun_bc_call (self_in=0x3002afd0, n_args=135084909, n_kw=0, args=0x0) at ../../py/objfun.c:288
#9  0x080d3b6c in mp_call_function_n_kw (fun_in=fun_in@entry=0x3002afd0, n_args=n_args@entry=0, n_kw=n_kw@entry=0, args=args@entry=0x0)
    at ../../py/runtime.c:652
#10 0x080d3b94 in mp_call_function_0 (fun=fun@entry=0x3002afd0) at ../../py/runtime.c:626
#11 0x080e339a in parse_compile_execute (source=<optimized out>, input_kind=input_kind@entry=MP_PARSE_FILE_INPUT, 
    exec_flags=exec_flags@entry=40) at ../../lib/utils/pyexec.c:119
#12 0x080e3766 in pyexec_str (str=<optimized out>) at ../../lib/utils/pyexec.c:697
#13 0x080b181a in main () at ports/stm32/main.c:741
(gdb) n
720	            while (!JPEG_input_paused) {
(gdb) 
721	                __WFI();
(gdb) 
723	                if (JPEG_output_paused) {
(gdb) 
720	            while (!JPEG_input_paused) {
(gdb) 
721	                __WFI();
(gdb) 
723	                if (JPEG_output_paused) {
(gdb) n
720	            while (!JPEG_input_paused) {
(gdb) 
721	                __WFI();
(gdb) 
723	                if (JPEG_output_paused) {
(gdb) 
720	            while (!JPEG_input_paused) {
```
Corrupted FB
![image](https://user-images.githubusercontent.com/4498013/116827838-81268d00-ab9b-11eb-8dee-95950930f195.png)

**Comment by iabdalkader** [comment]
Fixed, it was due to not soft-resetting in wifi debug mode.
