### ISSUE TITLE
 Nano RP2040 Connect Micropython MLC example OSError: [Errno 2] ENOENT

### ISSUE THREAD

**Issue by jomoengineer** [openmv/openmv#1566]
**Describe the bug**
When running the LSM6DSOX IMU MLC example, lsm6dsox_mlc.py, there is a message stating that it may be required to copy lsm6dsox to the RP2040 to run the example and when doing so, the script fails with the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "lsm6dsox.py", line 136, in __init__
  File "lsm6dsox.py", line 189, in load_mlc
OSError: [Errno 2] ENOENT
MPY: soft reboot
MicroPython: v1.17-omv-r22 OpenMV: v4.2.3 HAL: v1.3.0 BOARD: Arduino Nano RP2040 Connect-RP2040
Type "help()" for more information.
>>> 
```

If I remove the lsm6dsox.py window from the OpenMV IDE screen, the example seems to run without issue.
It appears the wrong file is being copied to the RP2040 for this example.

**To Reproduce**
1. Go to OpenMV IDE with the Nano RP2040 Connected connected, 
2. Click on File->Examples->Arduino->Nano RP2040->Sensors->
3. Scroll down to lsm6dsox_mlc.py
4. Run the script
5. An Import Helper - OpenMV IDE pop-up window will appear stating:
    Module "lsm6dsox" may be required to run your script
6. Click Yes and the file lsm6dsox.py is copied to the board
7. The error will be seen once the script runs
     NOTE: This appears to only occur the first time the script is run after a firmware install.
                The script seems to run as expected on subsequent tries.

**Expected behavior**
No error seen during starting of script and a prompt in the Serial Terminal showing "MLC Configured..." should appear. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10980402/156499533-f776c7e4-6841-4863-8c32-bf201de49792.png)

**Please complete the following information**
 - IDE version: 2.9.0
 - Firmware version: 4.2.3
 - Board: Arduino Nano RP2040 Connect
 - OS: Windows 10

**Comment by iabdalkader** [comment]
This is bug in the IDE, it copies the example script called `lsm6dsox.py` instead of copying the library `lsm6dsox.py`. The workaround is:
* Download the library https://raw.githubusercontent.com/openmv/openmv/master/scripts/libraries/lsm6dsox.py
* Copy to storage and safe remove, restart the board
* Connect, the IDE will ask you to update it (because it's different from the local file) click No
* The example should work (note you also need a model, see comments/links the example).
