### ISSUE TITLE
PureThermal RTC doesn't increment while board is powered off

### ISSUE THREAD

**Issue by griffin175** [openmv/openmv#1600]
**Describe the bug**
There is a known hardware issue with the RTC crystal. The load capacitance is too high.
[See issue 1536](https://github.com/openmv/openmv/issues/1536)
Removing C96 and C97 should resolve the issue, but it doesn't appear to be working.
I tried the posted procedure there, but I am unable to replicate working results.

I have tested multiple boards, with and without C96 and C97.

**To Reproduce**

1. Power off and disconnect battery and USB if applicable.
2. De-solder C96 and C97
3. Connect a charged battery to the 1S LiPo connector and connect to USB.
4. Connect to the IDE and add the following to the default main.py in `def main():`
```
    # RTC Testing
    from pyb import RTC
    rtc = RTC()
    #rtc.datetime((2022, 3, 5, 2, 9, 18, 0, 0)) # (YYYY, M, D, W, H, M, S, SubS)
    print(rtc.datetime())
```
This will read out the date and time to the serial terminal once when the script is run.
Main.py attached: [main.zip](https://github.com/openmv/openmv/files/8374278/main.zip)

5. Under Tools, click Save open script to OpenMV cam (as main.py)

6. Uncomment the line `rtc.datetime((2022, 3, 5, 2, 9, 18, 0, 0)) # (YYYY, M, D, W, H, M, S, SubS)` to set the 
Use any reasonable date and time.

7. Run the script to set the date and time.
8. Stop the script
9. Re-comment out the line `rtc.datetime((2022, 3, 5, 2, 9, 18, 0, 0)) # (YYYY, M, D, W, H, M, S, SubS)`
10. Disconnect the USB.
11. Power off the board.
The board may appear to be off after disconnecting, but it may still be powered on.
The RGB charge LED will flash red and fade out to indicate the board is powering off.

12. Wait 5 minutes.
13. Connect the board to USB
14. Power on the board
15. Connect to IDE
16. Run the script and check the serial monitor for the reported date and time.
If the date and time goes back to the original set date and time, double check you followed step 8.

Output on the terminal will look something like this:
```
(2022, 3, 5, 2, 9, 18, 0, 0)

Traceback (most recent call last):
  File "<stdin>", line 88, in <module>
  File "<stdin>", line 67, in main
Exception: IDE interrupt
MicroPython: 2d09a49 OpenMV: 63c4ce2 HAL: v1.9.0 BOARD: OPENMVPT-STM32H743
Type "help()" for more information.
>>> 

(2022, 3, 5, 2, 9, 18, 34, 949218)
```

**Expected behavior**
The reported time should be at least a few minutes in the future.
Instead, it is only about 34 seconds in the future. This seems to be about the time it takes to turn off the board and turn it back on.

To reiterate, I did try the same test procedures posted in Issue 1536 as well.
If someone spots something wrong with my procedure, please correct me and I'll test again.

 - IDE version: IDE 2.9.0
 - Firmware version: FW 4.3.1 and 4.3.0
 - Board: PureThermal OpenMV
 - OS: Windows 11

**Comment by griffin175** [comment]
Testing again with fw4.5.3, this issue appears to be fixed.
