### ISSUE TITLE
[Bug]struct.error: argument out of range

### ISSUE THREAD

**Issue by xielaoban-code** [openmv/openmv#1852]
![image](https://github.com/openmv/openmv/assets/92900942/3c1dc25a-2dd2-4c0d-a789-1365ea546e6e)

**Comment by xielaoban-code** [comment]
```
PS C:\Users\yujunyu\Desktop\23-05-26-openmv-det\pentagram\trans> python .\cascade_convert.py .\cascade.xml
Converting new XML format..
Traceback (most recent call last):
  File "C:\Users\yujunyu\Desktop\23-05-26-openmv-det\pentagram\trans\cascade_convert.py", line 426, in <module>
    main()
  File "C:\Users\yujunyu\Desktop\23-05-26-openmv-det\pentagram\trans\cascade_convert.py", line 423, in main
    cascade_binary_universal(args.file, args.stages, args.name)
  File "C:\Users\yujunyu\Desktop\23-05-26-openmv-det\pentagram\trans\cascade_convert.py", line 104, in cascade_binary_universal
    cascade_binary(path, n_stages, name)
  File "C:\Users\yujunyu\Desktop\23-05-26-openmv-det\pentagram\trans\cascade_convert.py", line 173, in cascade_binary
    fout.write(struct.pack('h', int(float(t.childNodes[0].nodeValue.split()[3])*4096))) #int16_t
struct.error: argument out of range
PS C:\Users\yujunyu\Desktop\23-05-26-openmv-det\pentagram\trans> python .\cascade_convert.py -i -n pentagram -s 8 .\cascade.xml
Parsing new XML format..
size:20x20
stages:8
features:24
rectangles:0
```

But cascade file is onle 1kb, it is not useful,exanple:
![image](https://github.com/openmv/openmv/assets/92900942/31d3e950-49be-47b5-a00c-d4e49e75dd71)
