### ISSUE TITLE
nn_quantizer.py runs indefinitely

### ISSUE THREAD

**Issue by laoonatic** [openmv/openmv#412]
Hi,

I am trying to quantize a modified model based on the lenet trained on the MNIST data set. I only retrained the last layer from the lenet_train_test.prototxt in [1] on my own data set. So what I did was:
- Change the input of the data layer to have the location on my new data
- Change the learning rates of all the layers except for the last one to 0
- Load the weights of the lenet model trained on the MNIST
- Train only the last layer

It all works well, except when I try to quantize the model using `nn_quantizer.py`. It doesn't seem to print any errors, but it keeps on hanging in a loop and run indefinitely. The output is the following:
```
$ python2 nn_quantizer.py --model data/lenet_train_test_modified.prototxt --weights data/weights.pretrained.caffemodel --save data/lenet_modified.pkl
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1116 10:39:16.540519 16351 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W1116 10:39:16.540547 16351 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W1116 10:39:16.540557 16351 _caffe.cpp:142] Net('data/lenet_train_test_modified.prototxt', 1, weights='data/weights.pretrained.caffemodel')
I1116 10:39:16.541888 16351 net.cpp:294] The NetState phase (1) differed from the phase (0) specified by a rule in layer mnist
I1116 10:39:16.541908 16351 net.cpp:51] Initializing net from parameters: 
name: "lenet_modified"
state {
  phase: TEST
  level: 0
}
layer {
  name: "mnist"
  type: "HDF5Data"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  hdf5_data_param {
    source: "test_h5_list.txt"
    batch_size: 50
  }
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 0
  }
  param {
    lr_mult: 0
  }
  convolution_param {
    num_output: 20
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv2"
  type: "Convolution"
  bottom: "pool1"
  top: "conv2"
  param {
    lr_mult: 0
  }
  param {
    lr_mult: 0
  }
  convolution_param {
    num_output: 50
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "conv2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "ip1"
  type: "InnerProduct"
  bottom: "pool2"
  top: "ip1"
  param {
    lr_mult: 0
  }
  param {
    lr_mult: 0
  }
  inner_product_param {
    num_output: 500
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "ip1"
  top: "ip1"
}
layer {
  name: "ip2_modified"
  type: "InnerProduct"
  bottom: "ip1"
  top: "ip2_modified"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  inner_product_param {
    num_output: 2
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "accuracy"
  type: "Accuracy"
  bottom: "ip2_modified"
  bottom: "label"
  top: "accuracy"
  include {
    phase: TEST
  }
}
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "ip2_modified"
  bottom: "label"
  top: "loss"
}
I1116 10:39:16.542081 16351 layer_factory.hpp:77] Creating layer mnist
I1116 10:39:16.542091 16351 net.cpp:84] Creating Layer mnist
I1116 10:39:16.542096 16351 net.cpp:380] mnist -> data
I1116 10:39:16.542109 16351 net.cpp:380] mnist -> label
I1116 10:39:16.542114 16351 hdf5_data_layer.cpp:80] Loading list of HDF5 filenames from: test_lop_h5_list.txt
I1116 10:39:16.542136 16351 hdf5_data_layer.cpp:94] Number of HDF5 files: 1
I1116 10:39:16.543126 16351 hdf5.cpp:32] Datatype class: H5T_FLOAT
I1116 10:39:16.544157 16351 net.cpp:122] Setting up mnist
I1116 10:39:16.544178 16351 net.cpp:129] Top shape: 50 1 28 28 (39200)
I1116 10:39:16.544186 16351 net.cpp:129] Top shape: 50 1 (50)
I1116 10:39:16.544190 16351 net.cpp:137] Memory required for data: 157000
I1116 10:39:16.544196 16351 layer_factory.hpp:77] Creating layer label_mnist_1_split
I1116 10:39:16.544204 16351 net.cpp:84] Creating Layer label_mnist_1_split
I1116 10:39:16.544211 16351 net.cpp:406] label_mnist_1_split <- label
I1116 10:39:16.544220 16351 net.cpp:380] label_mnist_1_split -> label_mnist_1_split_0
I1116 10:39:16.544231 16351 net.cpp:380] label_mnist_1_split -> label_mnist_1_split_1
I1116 10:39:16.544240 16351 net.cpp:122] Setting up label_mnist_1_split
I1116 10:39:16.544245 16351 net.cpp:129] Top shape: 50 1 (50)
I1116 10:39:16.544251 16351 net.cpp:129] Top shape: 50 1 (50)
I1116 10:39:16.544256 16351 net.cpp:137] Memory required for data: 157400
I1116 10:39:16.544261 16351 layer_factory.hpp:77] Creating layer conv1
I1116 10:39:16.544291 16351 net.cpp:84] Creating Layer conv1
I1116 10:39:16.544296 16351 net.cpp:406] conv1 <- data
I1116 10:39:16.544307 16351 net.cpp:380] conv1 -> conv1
I1116 10:39:16.544386 16351 net.cpp:122] Setting up conv1
I1116 10:39:16.544394 16351 net.cpp:129] Top shape: 50 20 24 24 (576000)
I1116 10:39:16.544399 16351 net.cpp:137] Memory required for data: 2461400
I1116 10:39:16.544407 16351 layer_factory.hpp:77] Creating layer pool1
I1116 10:39:16.544422 16351 net.cpp:84] Creating Layer pool1
I1116 10:39:16.544428 16351 net.cpp:406] pool1 <- conv1
I1116 10:39:16.544436 16351 net.cpp:380] pool1 -> pool1
I1116 10:39:16.544448 16351 net.cpp:122] Setting up pool1
I1116 10:39:16.544456 16351 net.cpp:129] Top shape: 50 20 12 12 (144000)
I1116 10:39:16.544463 16351 net.cpp:137] Memory required for data: 3037400
I1116 10:39:16.544469 16351 layer_factory.hpp:77] Creating layer conv2
I1116 10:39:16.544479 16351 net.cpp:84] Creating Layer conv2
I1116 10:39:16.544486 16351 net.cpp:406] conv2 <- pool1
I1116 10:39:16.544493 16351 net.cpp:380] conv2 -> conv2
I1116 10:39:16.544682 16351 net.cpp:122] Setting up conv2
I1116 10:39:16.544690 16351 net.cpp:129] Top shape: 50 50 8 8 (160000)
I1116 10:39:16.544699 16351 net.cpp:137] Memory required for data: 3677400
I1116 10:39:16.544709 16351 layer_factory.hpp:77] Creating layer pool2
I1116 10:39:16.544716 16351 net.cpp:84] Creating Layer pool2
I1116 10:39:16.544721 16351 net.cpp:406] pool2 <- conv2
I1116 10:39:16.544728 16351 net.cpp:380] pool2 -> pool2
I1116 10:39:16.544736 16351 net.cpp:122] Setting up pool2
I1116 10:39:16.544741 16351 net.cpp:129] Top shape: 50 50 4 4 (40000)
I1116 10:39:16.544749 16351 net.cpp:137] Memory required for data: 3837400
I1116 10:39:16.544754 16351 layer_factory.hpp:77] Creating layer ip1
I1116 10:39:16.544761 16351 net.cpp:84] Creating Layer ip1
I1116 10:39:16.544766 16351 net.cpp:406] ip1 <- pool2
I1116 10:39:16.544775 16351 net.cpp:380] ip1 -> ip1
I1116 10:39:16.547381 16351 net.cpp:122] Setting up ip1
I1116 10:39:16.547394 16351 net.cpp:129] Top shape: 50 500 (25000)
I1116 10:39:16.547400 16351 net.cpp:137] Memory required for data: 3937400
I1116 10:39:16.547411 16351 layer_factory.hpp:77] Creating layer relu1
I1116 10:39:16.547425 16351 net.cpp:84] Creating Layer relu1
I1116 10:39:16.547430 16351 net.cpp:406] relu1 <- ip1
I1116 10:39:16.547436 16351 net.cpp:367] relu1 -> ip1 (in-place)
I1116 10:39:16.547443 16351 net.cpp:122] Setting up relu1
I1116 10:39:16.547447 16351 net.cpp:129] Top shape: 50 500 (25000)
I1116 10:39:16.547452 16351 net.cpp:137] Memory required for data: 4037400
I1116 10:39:16.547457 16351 layer_factory.hpp:77] Creating layer ip2_modified
I1116 10:39:16.547466 16351 net.cpp:84] Creating Layer ip2_modified
I1116 10:39:16.547471 16351 net.cpp:406] ip2_modified <- ip1
I1116 10:39:16.547475 16351 net.cpp:380] ip2_modified -> ip2_modified
I1116 10:39:16.547493 16351 net.cpp:122] Setting up ip2_modified
I1116 10:39:16.547498 16351 net.cpp:129] Top shape: 50 2 (100)
I1116 10:39:16.547502 16351 net.cpp:137] Memory required for data: 4037800
I1116 10:39:16.547508 16351 layer_factory.hpp:77] Creating layer ip2_modified_ip2_modified_0_split
I1116 10:39:16.547513 16351 net.cpp:84] Creating Layer ip2_modified_ip2_modified_0_split
I1116 10:39:16.547518 16351 net.cpp:406] ip2_modified_ip2_modified_0_split <- ip2_modified
I1116 10:39:16.547523 16351 net.cpp:380] ip2_modified_ip2_modified_0_split -> ip2_modified_ip2_modified_0_split_0
I1116 10:39:16.547528 16351 net.cpp:380] ip2_modified_ip2_modified_0_split -> ip2_modified_ip2_modified_0_split_1
I1116 10:39:16.547535 16351 net.cpp:122] Setting up ip2_modified_ip2_modified_0_split
I1116 10:39:16.547538 16351 net.cpp:129] Top shape: 50 2 (100)
I1116 10:39:16.547544 16351 net.cpp:129] Top shape: 50 2 (100)
I1116 10:39:16.547547 16351 net.cpp:137] Memory required for data: 4038600
I1116 10:39:16.547551 16351 layer_factory.hpp:77] Creating layer accuracy
I1116 10:39:16.547557 16351 net.cpp:84] Creating Layer accuracy
I1116 10:39:16.547561 16351 net.cpp:406] accuracy <- ip2_modified_ip2_modified_0_split_0
I1116 10:39:16.547566 16351 net.cpp:406] accuracy <- label_mnist_1_split_0
I1116 10:39:16.547571 16351 net.cpp:380] accuracy -> accuracy
I1116 10:39:16.547577 16351 net.cpp:122] Setting up accuracy
I1116 10:39:16.547581 16351 net.cpp:129] Top shape: (1)
I1116 10:39:16.547585 16351 net.cpp:137] Memory required for data: 4038604
I1116 10:39:16.547590 16351 layer_factory.hpp:77] Creating layer loss
I1116 10:39:16.547595 16351 net.cpp:84] Creating Layer loss
I1116 10:39:16.547600 16351 net.cpp:406] loss <- ip2_modified_ip2_modified_0_split_1
I1116 10:39:16.547606 16351 net.cpp:406] loss <- label_mnist_1_split_1
I1116 10:39:16.547612 16351 net.cpp:380] loss -> loss
I1116 10:39:16.547621 16351 layer_factory.hpp:77] Creating layer loss
I1116 10:39:16.547642 16351 net.cpp:122] Setting up loss
I1116 10:39:16.547646 16351 net.cpp:129] Top shape: (1)
I1116 10:39:16.547652 16351 net.cpp:132]     with loss weight 1
I1116 10:39:16.547664 16351 net.cpp:137] Memory required for data: 4038608
I1116 10:39:16.547670 16351 net.cpp:198] loss needs backward computation.
I1116 10:39:16.547677 16351 net.cpp:200] accuracy does not need backward computation.
I1116 10:39:16.547683 16351 net.cpp:198] ip2_modified_ip2_modified_0_split needs backward computation.
I1116 10:39:16.547686 16351 net.cpp:198] ip2_modified needs backward computation.
I1116 10:39:16.547693 16351 net.cpp:200] relu1 does not need backward computation.
I1116 10:39:16.547698 16351 net.cpp:200] ip1 does not need backward computation.
I1116 10:39:16.547703 16351 net.cpp:200] pool2 does not need backward computation.
I1116 10:39:16.547708 16351 net.cpp:200] conv2 does not need backward computation.
I1116 10:39:16.547713 16351 net.cpp:200] pool1 does not need backward computation.
I1116 10:39:16.547719 16351 net.cpp:200] conv1 does not need backward computation.
I1116 10:39:16.547724 16351 net.cpp:200] label_mnist_1_split does not need backward computation.
I1116 10:39:16.547730 16351 net.cpp:200] mnist does not need backward computation.
I1116 10:39:16.547735 16351 net.cpp:242] This network produces output accuracy
I1116 10:39:16.547740 16351 net.cpp:242] This network produces output loss
I1116 10:39:16.547751 16351 net.cpp:255] Network initialization done.
```

When I force stop the script, it seems to be hanging in the following place:
```
^CTraceback (most recent call last):
  File "nn_quantizer.py", line 608, in <module>
    my_model.get_graph_connectivity()
  File "nn_quantizer.py", line 241, in get_graph_connectivity
    if (current_blob in value) and (key not in traversed) and \
KeyboardInterrupt
```
I tried using pdb to identify the problem, but I still don't seem to get what's wrong, especially as I don't get any error message. Also, the network uses the same types of layers as in the MNIST model example, so I expected it to work here. The only difference is the data layer, which takes as input an HDF5 database (as opposed to an LMDB one). However, I didn't find any warning about this not being supported.

If anybody has any ideas about what's going wrong, I would be grateful. Thank you!

[1] https://github.com/BVLC/caffe/tree/master/examples/mnist

**Comment by laoonatic** [comment]
An update: I tried running the quantizer on the same model, but using an LMDB data layer for the input and it worked. So the issue is probably the HDF5 data layer. Is this issue known? If yes, then maybe consider adding a warning or something about it in the documentation?

**Comment by kwagyeman** [comment]
Hi, I still need to merge this PR: https://github.com/kwagyeman/openmv/tree/more_nn_nets/ml/cmsisnn

**Comment by kwagyeman** [comment]
It is a lot more documented.

**Comment by iabdalkader** [comment]
Those are the supported layers:
https://github.com/openmv/openmv/blob/master/ml/cmsisnn/nn_quantizer.py#L219

The type needs to be "data" or "5" for the data layer:
https://github.com/openmv/openmv/blob/master/ml/cmsisnn/nn_quantizer.py#L201

Nout our converter script expects "data" for the data layer type.

**Comment by laoonatic** [comment]
Thank you for your answers, they are really helpful.
